### PR TITLE
Use Faraday middleware on Uploadcare connections only.

### LINKED ISSUE #13: Breaking the Twitter Gem
It appears the [ParseJson Faraday middleware](https://github.com/uploadcare/uploadcare-ruby/blob/master/lib/uploadcare/rest/middlewares/parse_json_middleware.rb) your injecting is interfering with requests made from the [Twitter gem](https://github.com/sferik/twitter) in our case [here](https://github.com/sferik/twitter/blob/v5.11.0/lib/twitter/identity.rb#L15). In this example the keys in the `attrs` Hash are meant to be Symbols rather than Strings which means the `fetch` errors out as it can't find a key name `:id`.

### PR DESCRIPTION
**Pull request by damian**
Fixes #13.

I think the original Uploadcare specific Faraday middlewares were
effecting all connections made by Faraday.

Also ensure that the rspec runner has coloured output :)

### CODE REVIEW

**Comment by dmitry-mukhin** [comment]
@damian, can you make tests pass?

**Comment by damian** [comment]
When I checked earlier they were already failing before my commit. Will take another look later tonight to see what I can do.

**Comment by dmitry-mukhin** [comment]
yup, ruby gem needs some love :(

**Comment by dmitry-mukhin** [comment]
@vizvamitra please take a look if we can salvage this

**Comment by vizvamitra** [comment]
Fixed in #24

**Comment by damian** [comment]
Thank you chaps 👍

**Pull request closed without merging**
