### PR TITLE
Enables automatic storing when uploading file

### PR DESCRIPTION
**Pull request by Meekohi**
One implementation detail is that the API will only "not store" only if the `store` param is missing or `store:0`. `store:'false'` will not work (the API will evaluate that to true and store anyway)

### CODE REVIEW

**Comment by vizvamitra** [comment]
@Meekohi thanks for your contribution. 

I'm currently working on adding support of UPLOADCARE_STORE flag (see [upload api docs][1]). This change will include a fix to your problem. WIP branch can be found [here][2]. I beleve I'll finish it in a couple of days

[1]: https://uploadcare.com/documentation/upload/
[2]: https://github.com/vizvamitra/uploadcare-ruby/tree/feature/UPLOADCARE_STORE_upload_flag

**Comment by dmitry-mukhin** [comment]
@Meekohi, @vizvamitra's changes seem to be more fundamental. can you check if his branch works for you?

**Comment by Meekohi** [comment]
Works for me -- looks like a good more general solution in case there are more flags in the future.

**Comment by dmitry-mukhin** [comment]
closes in favour of #36

**Pull request closed without merging**
